const PANTRY_MATCHING_CONFIG = {
  unitFamilies: {
    mass: ["g", "kg"],
    volume: ["ml", "l"],
    count: ["pcs", "pack", "bottle", "can"],
  },
  spoonToMl: {
    tbsp: 15,
    tsp: 5,
  },
  unitAliasMap: {
    g: "g",
    gr: "g",
    gram: "g",
    grams: "g",
    gam: "g",
    kg: "kg",
    kilogram: "kg",
    kilograms: "kg",
    ml: "ml",
    milliliter: "ml",
    milliliters: "ml",
    mililiter: "ml",
    mililiters: "ml",
    l: "l",
    lit: "l",
    liter: "l",
    litre: "l",
    liters: "l",
    litres: "l",
    tbsp: "tbsp",
    tablespoon: "tbsp",
    tablespoons: "tbsp",
    "muong canh": "tbsp",
    "muong an": "tbsp",
    tsp: "tsp",
    teaspoon: "tsp",
    teaspoons: "tsp",
    "muong ca phe": "tsp",
    "muong cafe": "tsp",
    "muong tra": "tsp",
    "muong nho": "tsp",
    pc: "pcs",
    pcs: "pcs",
    piece: "pcs",
    pieces: "pcs",
    mieng: "pcs",
    qua: "pcs",
    trai: "pcs",
    cu: "pcs",
    cai: "pcs",
    pack: "pack",
    goi: "pack",
    bottle: "bottle",
    chai: "bottle",
    can: "can",
    lon: "can",
  },
  nameStopWords: [
    "tuoi",
    "xay",
    "bam",
    "thai",
    "cat",
    "ngam",
    "mem",
    "chin",
    "song",
    "it",
    "vua",
    "kieu",
    "fresh",
    "dried",
    "chopped",
    "minced",
  ],
};

export default PANTRY_MATCHING_CONFIG;
